<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
  Author: Felix Messmer
-->

  <xacro:include filename="$(find ur_description)/urdf/ur.transmission.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur.gazebo.xacro" />

  <property name="pi" value="3.14159265" />

  <!-- Inertia parameters -->
  <property name="base_mass" value="2.0" />  <!-- This mass might be incorrect -->
  <property name="shoulder_mass" value="2.0" />
  <property name="upper_arm_mass" value="3.42" />
  <property name="forearm_mass" value="1.26" />
  <property name="wrist_1_mass" value="0.8" />
  <property name="wrist_2_mass" value="0.8" />
  <property name="wrist_3_mass" value="0.35" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <property name="shoulder_cog" value="0.0 -0.02 0.0" />
  <property name="upper_arm_cog" value="0.13 0.0 0.1157" />
  <property name="forearm_cog" value="0.05 0.0 0.0238" />
  <property name="wrist_1_cog" value="0.0 0.0 0.01" />
  <property name="wrist_2_cog" value="0.0 0.0 0.01" />
  <property name="wrist_3_cog" value="0.0 0.0 -0.02" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <property name="ur3_d1" value="0.1519" />
  <property name="ur3_a2" value="-0.24365" />
  <property name="ur3_a3" value="-0.21325" />
  <property name="ur3_d4" value="0.11235" />
  <property name="ur3_d5" value="0.08535" />
  <property name="ur3_d6" value="0.0819" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <property name="shoulder_offset" value="0.1198" />  <!-- measured from model -->
  <property name="elbow_offset" value="-0.0925" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <property name="shoulder_height" value="${ur3_d1}" />
  <property name="upper_arm_length" value="${-ur3_a2}" />
  <property name="forearm_length" value="${-ur3_a3}" />
  <property name="wrist_1_length" value="${ur3_d4 - elbow_offset - shoulder_offset}" />
  <property name="wrist_2_length" value="${ur3_d5}" />
  <property name="wrist_3_length" value="${ur3_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur3_robot" params="prefix joint_limited">

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur3_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur3_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur3_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur3_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur3/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}ee_fixed_joint" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>

    <xacro:ur_arm_transmission prefix="${prefix}" />
    <xacro:ur_arm_gazebo prefix="${prefix}" />

    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
      <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${prefix}tool0"/>
    <joint name="${prefix}wrist_3_link-tool0_fixed_joint" type="fixed">
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="${prefix}wrist_3_link"/>
      <child link="${prefix}tool0"/>
    </joint>



<!--first my program -->
    <!--Fixing frame_force_vision_sensor -->
    <link name="${prefix}ur5_suction_claw">
      <inertial>
        <origin xyz="0 0 0.004" rpy="0 0 0"/>
        <mass value="1.2"/>
        <inertia ixx="0.0001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
     </inertial>
     
      <visual>
        <origin xyz="-0.083 -0.0925 -0.004" rpy="${pi/2.0} 0 ${pi/2.0}"/>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur5/collision/ur5_suction_claw.stl"/>
        </geometry>
        <material name="LightGrey"/>
         <color rgba="0.7 0.7 0.7 1"/> 
      </visual> 
      
      <!--collision for rgbd -->
      <collision>
        <geometry>
          <box size="0.18 0.05 0.05"/>
        </geometry>
        <origin xyz="-0.007 -0.07 0.025" rpy="0 0 0 "/>
      </collision>  

       <!--collision cpu -->
       <collision>
        <geometry>
          <box size="0.022 0.034 0.022"/>
        </geometry>
        <origin xyz="-0.007 0.088 0.132" rpy="0 0 0 "/>
       </collision>  

       <!--collision rgb -->
       <collision>
        <geometry>
          <box size="0.12 0.05 0.085"/>
        </geometry>
        <origin xyz="-0.007 -0.11 0.04" rpy="0 0 0 "/>
       </collision>  

      <!--collision for gripper ,without force sensor -->
      <collision>
        <geometry>
          <cylinder radius="0.075" length="0.190"/>
        </geometry>
        <origin xyz="0 0 0.095" rpy="0 0 0 "/>
      </collision> 
    </link>
    
    <joint name="${prefix}wrist_3_link_ur5_suction_claw_fixed_joint" type="fixed">
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} ${pi/2.0} 0"/>
      <parent link="${prefix}wrist_3_link"/>
      <child link="${prefix}ur5_suction_claw"/>
    </joint>

  <!-- claw_Memory_chip--><!--just create coordinate -->
  <link name="${prefix}claw_Memory_chip"/>
  <joint name="${prefix}ur5_suction_claw_claw_Memory_chip_fixed_joint" type="fixed">
    <origin xyz="0 0 0.173" rpy="${3*pi/2.0} 0 0"/>       <!-- change 0.173,direction root 0.0045 -->
    <parent link="${prefix}ur5_suction_claw"/>
    <child link="${prefix}claw_Memory_chip"/>
  </joint>  

  <!-- claw_steek--><!--just create coordinate -->
  <link name="${prefix}claw_steel"/>
  <joint name="${prefix}ur5_suction_claw_claw_steel_fixed_joint" type="fixed">
    <origin xyz="0 0 0.173" rpy="0 0 0"/>       <!-- change 0.173,direction root 0.0045 -->
    <parent link="${prefix}ur5_suction_claw"/>
    <child link="${prefix}claw_steel"/>
  </joint>  
    
  <!-- suction_cup2--><!--just create coordinate -->
  <link name="${prefix}suction_cup"/>
  <joint name="${prefix}ur5_suction_claw_suction_cup_fixed_joint" type="fixed">
    <origin xyz="0 0.057 0.197" rpy="0 0 0"/>
    <parent link="${prefix}ur5_suction_claw"/>
    <child link="${prefix}suction_cup"/>
  </joint>  

  <!--depth camera--><!--just create coordinate -->
  <link name="${prefix}depth_camera"/>
  <joint name="${prefix}ur5_suction_claw_depth_camera_fixed_joint" type="fixed">
    <origin xyz="0.0 -0.07 0.0" rpy="0 0 0"/>
    <parent link="${prefix}ur5_suction_claw"/>
    <child link="${prefix}depth_camera"/>
  </joint>  
   <!--TODO add weight property for sensors -->
  </xacro:macro>
</robot>
